site_name: 一只Tom的笔记本
site_url: https://tomsjtu.github.io/notes/
repo_url: https://github.com/TomSjtu/notes
site_description: 一只Tom的笔记本
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - c
    - c++
nav:
  - Home: index.md

  - Linux: linux/linux.md

  - Arm: arm/arm.md

  - 编程语言: pl/pl.md

  - Tools: tools/tools.md