site_name: 一只Tom的笔记本
site_url: https://tomsjtu.github.io/notes/
repo_url: https://github.com/TomSjtu/notes
site_description: 一只Tom的笔记本
site_author: Tom

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - c
    - c++
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - navigation.top
    - content.code.copy
     
  palette:
    primary: light blue
 

  font: false

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Linux: 
    - linux/index.md
    - 内核剖析:
      - linux/kernel/index.md
      - linux/kernel/intro.md
      - linux/kernel/task.md
      - linux/kernel/sched.md
      - linux/kernel/ipc.md
      - linux/kernel/vma.md
      - linux/kernel/interrupt.md
      - linux/kernel/synch.md
      - linux/kernel/mm.md
      - linux/kernel/page.md
      - linux/kernel/vfs.md
      - linux/kernel/block.md
      - linux/kernel/network.md
      - linux/kernel/time.md
      - linux/kernel/pm.md
      - linux/kernel/others.md
      
    
    - 设备驱动程序:
      - linux/drivers/index.md
      - linux/drivers/hardware.md
      - linux/drivers/protocol.md
      - linux/drivers/module.md
      - linux/drivers/dts.md
      - linux/drivers/interrupt.md
      - linux/drivers/dma.md
      - linux/drivers/device_model.md
      - linux/drivers/platform.md
      - linux/drivers/chardev.md
      - linux/drivers/blkdev.md
      - linux/drivers/netdev.md
      - linux/drivers/pinctrl.md
      - linux/drivers/gpio.md
      - linux/drivers/i2c.md
      - linux/drivers/spi.md
      - linux/drivers/uart.md
      - linux/drivers/input.md
      - linux/drivers/ethernet.md
      - linux/drivers/pci.md
      - linux/drivers/usb.md
      - linux/drivers/mmc.md
      - linux/drivers/wifi.md
      - linux/drivers/bluetooth.md
            

    - 性能调优:
      - linux/optimization/index.md
      - linux/optimization/cpu.md
      - linux/optimization/memory.md
      - linux/optimization/disk.md
      - linux/optimization/network.md

    - ebpf:
      - linux/ebpf/index.md
 
  - ARM: 
    - arm/index.md
    - arm/boot.md
    - arm/aarch64.md
    - arm/instructions.md
    - arm/assembler.md
    - arm/lock.md
    - arm/barrier.md
    - arm/gic.md

  - RTOS:
    - rtos/index.md
    - freertos:
      - rtos/freertos/index.md
    - CMSIS: rtos/freertos/CMSIS.md
    - rt-thread:
      - rtos/rt-thread/index.md

  - 编程语言: 
    - pl/index.md
    - C:
      - pl/gnu_c.md
    
    - 现代C++:
      - pl/modern_cpp.md
    
    - QT:
      - pl/qt.md

    - Python:
      - pl/python.md
    

  - 云计算:
    - cloud/index.md
    - cloud/docker.md

  - Tools: 
    - tools/index.md
    - tools/github.md
    - tools/vim.md
    - tools/markdown.md

  - 其他:
    - others/index.md
    - others/poker.md
    