site_name: 一只Tom的笔记本
site_url: https://tomsjtu.github.io/notes/
repo_url: https://github.com/TomSjtu/notes
site_description: 一只Tom的笔记本
site_author: Tom

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - c
    - c++
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.integrate
    - navigation.top
     
  palette:
    primary: light blue
 

  font: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Linux: 
    - linux/index.md
    - 内核剖析:
      - linux/kernel/synch.md
      - linux/kernel/others.md
    
    - 设备驱动程序:
      - linux/drivers/dts.md
      - linux/drivers/chardev.md
      

  - Arm: 
    - arm/index.md

  - 编程语言: 
    - pl/index.md

  - 云原生:
    - cloud/index.md

  - Tools: 
    - tools/index.md

