site_name: 一只Tom的笔记本
site_url: https://tomsjtu.github.io/notes/
repo_url: https://github.com/TomSjtu/notes
site_description: 一只Tom的笔记本
site_author: Tom

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - c
    - c++
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share
    
     
  palette:
    primary: light blue
 

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - def_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: 
  - pymdownx.inlinehilite
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Linux: 
    - linux/index.md
    - 内核剖析:
      - linux/kernel/index.md
      - linux/kernel/compile.md
      - linux/kernel/program.md
      - linux/kernel/debug.md
      - linux/kernel/synch.md
      - linux/kernel/others.md
      - linux/kernel/task.md
      - linux/kernel/sched.md
      - linux/kernel/ipc.md
      - linux/kernel/preempt.md
      - linux/kernel/kthread.md
      - linux/kernel/interrupt.md
      - linux/kernel/bottom_half.md
      - linux/kernel/mm.md
      - linux/kernel/vma.md
      - linux/kernel/recycle.md
      - linux/kernel/oom.md
      - linux/kernel/ion.md
      - linux/kernel/cma.md
      - linux/kernel/vfs.md
      - linux/kernel/block.md
      - linux/kernel/network.md
      - linux/kernel/time.md
      - linux/kernel/timer.md
      - linux/kernel/hrtimer.md
      - linux/kernel/pm.md
      - linux/kernel/shell.md
      
      
    
    - 设备驱动程序:
      - linux/drivers/index.md
      - linux/drivers/hardware.md
      - linux/drivers/protocol.md
      - linux/drivers/module.md
      - linux/drivers/dts.md
      - linux/drivers/interrupt.md
      - linux/drivers/dma.md
      - linux/drivers/device_model.md
      - linux/drivers/platform.md
      - linux/drivers/chardev.md
      - linux/drivers/blkdev.md
      - linux/drivers/netdev.md
      - linux/drivers/pinctrl.md
      - linux/drivers/gpio.md
      - linux/drivers/i2c.md
      - linux/drivers/spi.md
      - linux/drivers/uart.md
      - linux/drivers/input.md
      - linux/drivers/ethernet.md
      - linux/drivers/pcie.md
      - linux/drivers/usb.md
      - linux/drivers/wifi.md
      - linux/drivers/bluetooth.md
      - linux/drivers/socketcan.md
            

    - 性能调优:
      - linux/optimization/index.md
      - linux/optimization/cpu.md
      - linux/optimization/memory.md
      - linux/optimization/disk.md
      - linux/optimization/network.md

    - ebpf:
      - linux/ebpf/index.md
      - linux/ebpf/intro.md
      - linux/ebpf/ftrace.md
      - linux/ebpf/probe.md
      - linux/ebpf/bpftool.md
 
  - ARM: 
    - arm/index.md
    - arm/secure_boot.md
    - arm/boot.md
    - arm/aarch64.md
    - arm/standard.md
    - arm/instructions.md
    - arm/assembler.md
    - arm/exception.md
    - arm/gic.md
    - arm/atomic.md
    - arm/lock.md
    - arm/barrier.md
    - arm/mm.md
    - arm/cache.md
    - arm/tlb.md


  - ROS2:
    - ros2/index.md
    - ros2/intro.md
    - ros2/core.md


  - 编程语言: 
    - pl/index.md
    - C:
      - pl/c/standard.md
      - pl/c/gcc.md
      - pl/c/misc.md
    
    - C++:
      - pl/cpp/index.md
      - pl/cpp/misc.md
      - pl/cpp/io.md
      - pl/cpp/exception.md
      - pl/cpp/gdb.md
      - pl/cpp/cmake.md
      - pl/cpp/conan.md
      - pl/cpp/oop.md
      - pl/cpp/container.md
      - pl/cpp/algorithm.md
      - pl/cpp/regex.md
      - pl/cpp/time.md
      - pl/cpp/mm.md
      - pl/cpp/concurrency.md
      - pl/cpp/cpp11.md
    
    - QT:
      - pl/qt/qt.md

    - Python:
      - pl/python/python.md

    - Go:
      - pl/go/index.md
      - pl/go/intro.md
      - pl/go/function.md
      - pl/go/package.md

  - 人工智能:
    - ai/index.md
    - 深度学习:
      - ai/dl/index.md
      - ai/dl/onnx.md

  - 云计算:
    - cloud/index.md
    - cloud/docker.md

  - Tools: 
    - tools/index.md
    - tools/github.md
    - tools/vim.md
    - tools/markdown.md

  - 其他:
    - others/index.md
    - others/config.md
    - others/serializer.md
    - others/video.md
    - others/ffmpeg.md


    