site_name: 一只Tom的笔记本
site_url: https://tomsjtu.github.io/notes/
repo_url: https://github.com/TomSjtu/notes
site_description: 一只Tom的笔记本
site_author: Tom
theme:
  name: slate
  highlightjs: true
  hljs_languages:
    - c
    - c++
  feature:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  font: false

nav:
  - Home: index.md

  - Linux: 
    - linux/index.md

  - Arm: 
    - arm/index.md

  - 编程语言: 
    - pl/index.md

  - 云原生:
    - cloud/index.md

  - Tools: 
    - tools/index.md